name: Test script against windows docker container

on:
  push:
    branches: [cicd-test-branch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build -t simeononsecurity/windows-optimize-harden-debloat:latest --progress=plain .
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: simeononsecurity/windows-optimize-harden-debloat:latest
