name: Docker Image CI

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t simeononsecurity/windows-optimize-harden-debloat:latest . && \
          docker build -t ghcr.io/simeononsecurity/windows-optimize-harden-debloat:latest .

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            simeononsecurity/windows-optimize-harden-debloat:latest 
            ghcr.io/simeononsecurity/windows-optimize-harden-debloat:latest 


